# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ffc58419196ce86db1cf305c00f5d87e2d2bc3aba3de62b84a0de4f9b8b3d4d6d03fc8c9489a8b9e4c943f509881be82a3f60205e8e3b8fd6289582ee9bd7f8

test:
  secret_key_base: 6a3af0ac0b7c75dc8c9e6f1b1c55805a8930d0abba7fa3eef32429bdb312e736a081af1d47f6d5897be7908cabc3cd3d2245cad2a47fa32ac161ca65e7811325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
